# Railway.app configuration for Blood Bank AI System

[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# DHIS2 Service
[[services]]
name = "dhis2-service"
source = "services/dhis2-service"

[services.deploy]
healthcheckPath = "/api/v1/health/live"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[services.deploy.env]
PORT = "8001"
RAILWAY_STATIC_URL = "https://dhis2-service-production.up.railway.app"

[[services.deploy.volumeMounts]]
path = "/app/logs"
name = "logs"

# PostgreSQL Database
[[services]]
name = "postgres"
plugin = "postgresql"

[services.deploy.env]
POSTGRES_DB = "blood_bank_db"

# Redis Cache
[[services]]
name = "redis"
plugin = "redis"

# Variables partagées entre les services
[env]
# Application
APP_NAME = "DHIS2 Blood Bank Service"
APP_VERSION = "1.0.0"
DEBUG = "false"
LOG_LEVEL = "INFO"

# API Configuration
API_V1_STR = "/api/v1"
HOST = "0.0.0.0"

# Monitoring
ENABLE_METRICS = "true"
METRICS_PORT = "8002"

# Health Check
HEALTH_CHECK_TIMEOUT = "5"

# Rate Limiting
RATE_LIMIT_PER_MINUTE = "100"

# Retry Configuration
MAX_RETRY_ATTEMPTS = "3"
RETRY_DELAY = "1"

# DHIS2 API Version
DHIS2_API_VERSION = "40"

# Security
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
ALGORITHM = "HS256"

# Performance
DB_POOL_SIZE = "20"
DB_MAX_OVERFLOW = "30"
DB_POOL_TIMEOUT = "30"
DB_POOL_RECYCLE = "3600"

# Logging
LOG_FORMAT = "json"
LOG_ROTATION = "daily"
LOG_RETENTION_DAYS = "30"

# Localization
DEFAULT_TIMEZONE = "Africa/Douala"
DEFAULT_LANGUAGE = "fr"
SUPPORTED_LANGUAGES = "fr,en"

# Feature Flags
ENABLE_AUDIT_LOGGING = "true"
ENABLE_RATE_LIMITING = "true"
ENABLE_CORS = "true"
ENABLE_SWAGGER_UI = "true"